function [Names,DiabetesHealthy1,scaleOS,scaleOD] = getPatientsData(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE1 Import data from a spreadsheet
%   [Names,DiabetesHealthy1,scaleOS,scaleOD] = IMPORTFILE1(FILE) reads data
%   from the first worksheet in the Microsoft Excel spreadsheet file named
%   FILE and returns the data as column vectors.
%
%   [Names,DiabetesHealthy1,scaleOS,scaleOD] = IMPORTFILE1(FILE,SHEET)
%   reads from the specified worksheet.
%
%   [Names,DiabetesHealthy1,scaleOS,scaleOD] =
%   IMPORTFILE1(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   [Names,DiabetesHealthy1,scaleOS,scaleOD] = importfile1('patientsInfo.xlsx','Sheet1',2,29);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2018/12/06 09:15:10

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 45;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:D%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:D%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,1);
raw = raw(:,[2,3,4]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Names = cellVectors(:,1);
DiabetesHealthy1 = data(:,1);
scaleOS = data(:,2);
scaleOD = data(:,3);

